paths:
  output_dir: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/results"
  target_templates:
    linked_files: "linked_files/{0[individual]}/{0[sample_type]}"
    cellranger_count: "cellranger_count/{0[individual]}_{0[sample_type]}/outs"
    samples_sheet: "metadata/samples.csv"
references:
  all_masked: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/data/masked_reference/GRCm38_masked_all_strains"
  CAST_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_cast/"
  SPRET_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
  C57BL6J: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
metadata:
  raw:
   - "~/projects/bonemarrow-study/data/otp-export/2022-09-21/OE0538_DO-0008_mmus/data-files.csv"
  identifiers:
    - SAMPLE_NAME
    - Sample_Type
    - Age
    - fraction
  # Define all columns from the metadata spreadsheet that
  # will be included in the SingleCellExperiment / Seurat
  # objects
  single_cell_object_metadata_fields:
      - SAMPLE_NAME
      - Age
# Enable / Disable rules and specifiy rule-specific parameters
rules:
  cellranger_count:
    extra: ""  # set additional arguments for cellranger count
  allele_specific: False
  wasp_filter_reads: False
  realign_bam: False
