paths:
  output_dir: "/omics/groups/OE0538/internal/users/l012t/snakemake-cellranger/data"
  target_templates:
    linked_files: "linked_files/{0[individual]}"
    cellranger_count: "cellranger_count/{0[individual]}/outs"
    samples_sheet: "metadata/samples.csv"
    construct_sce_objects: "sce_objects/{0[individual]}"
  # define specific target files
  target_files:
    samples_sheet: "metadata.csv"
references:
  all_masked: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/data/masked_reference/GRCm38_masked_allStrains"
  #CAST_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_cast/"
  #SPRET_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
  #C57BL6J: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
metadata:
  raw:
   - "/omics/groups/OE0538/internal/users/l012t/snakemake-cellranger/data/metadata_full.csv"
  identifier:
    #- Species_ID # not needed atm since I already have only one species
    #- Age_ID
    #- Fraction_ID 
    #- Sample_NR
     - Object_ID
  # Define all columns from the metadata spreadsheet that
  # will be included in the SingleCellExperiment / Seurat
  # objects
  single_cell_object_metadata_fields:
      - Object_ID
      - Mouse_ID
      - Species_ID
      - Age
      - Age_ID
      - Age_weeks
      - Fraction
      - Fraction_ID
      - Antibody_combination
      - Sample_NR
      - Extrarun
      - Batch_exp_day
      - Batch_sequencing
      - Date_collected
      - Discard
      - PID
# Enable / Disable rules and specifiy rule-specific parameters
rules:
  cellranger_count:
  #  extra: ""  # set additional arguments for cellranger count
  allele_specific: False
  wasp_filter_reads: False
  realign_bam: False