paths:
  output_dir: "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
  target_templates:
    linked_files: "cellranger/linked_files/{0[Species_ID]}/{0[individual]}"
    cellranger_count: "cellranger/cellranger_count/{0[Species_ID]}/{0[individual]}/outs"
    construct_sce_objects: "sce_objects/archive/01_cellranger_output/{0[Species_ID]}/sce_{0[individual]}-01"
  # define specific target files
  target_files:
    samples_sheet: "metadata.csv"
references:
  all_masked: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/data/masked_reference/GRCm38_masked_allStrains"
  #CAST_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_cast/"
  #SPRET_EiJ: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
  #C57BL6J: "/omics/groups/OE0538/internal/users/panten/projects/genome_files/CellRangerRNA/B6_masked_spret/"
metadata:
  raw:
   - "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/OE0538_DO-0008_metadata_combined.csv"
  identifiers: 
  # Define column name(s) used to define a sample (in correct order)
  # entries from multiple cols are concatenated into one sample-specific name
  # in the format of {Species_ID}_{Age_ID}_{Fraction_ID}_{Sample_NR}
    - Species_ID # col names I manually added to metadata sheet beforehand
    - Age_ID
    - Fraction_ID 
    - Sample_NR
    #- Objects_ID 
    #- PID # col name automatically included in OTP metadata sheets
    #- Sample Type # col name automatically included in OTP metadata sheets
  single_cell_object_metadata_fields:
  # Define all columns from the metadata spreadsheet that
  # will be included in the SingleCellExperiment / Seurat
  # objects
      - Object_ID # colnames I manually added to metadata 
      - Mouse_ID
      - Species_ID
      - Age
      - Age_ID
      - Age_weeks
      - Fraction
      - Fraction_ID
      - Antibody_combination
      - Sample_NR
      - Extrarun
      - Batch_exp_day
      - Batch_sequencing
      - Date_collected
      - Keep_sample
      - individual
      - PID
# Enable / Disable rules and specifiy rule-specific parameters
rules:
  cellranger_count:
  #  extra: ""  # set additional arguments for cellranger count
  allele_specific: False
  wasp_filter_reads: False
  realign_bam: False