name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--lint --configfile config/config-example.yaml'
      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda  --configfile config/config-example.yaml --conda-cleanup-pkgs cache'
          stagein: '' # additional preliminary commands to run (can be multiline)
      - name: Create container file
        uses: snakemake/snakemake-github-action@v1
        with:
          snakefile: 'workflow/Snakefile'
          task: 'containerize'